fix image creation with local debian packages
aerokube/images pull request #418
Opened 2021-08-04 20:47 UTC by lorsatti

Related to #417.

2021-08-08 04:47 UTC, vania-pooh commented
@lorsatti sorry for the delay. Being on vacation and will check in detail during next days.

2021-08-08 10:38 UTC, lorsatti commented
Np. Enjoy your vacation!

2021-08-16 04:18 UTC, vania-pooh requested changes
Sorry that is took so much time to review. Need to use `filepath.Join` everywhere instead of `/`. See my first comment. All the rest seems to be ok.

2021-08-16 04:18 UTC, vania-pooh commented on build/chrome.go
> +		err := os.MkdirAll(devDestDir+"/"+srcDir, 0755)
Should use `filepath.Join` to make file path separator platform-independent. Just declare `pkgDestDir := filepath.Join(devDestDir, srcDir)` and also use this value in `pkgDestPath` initialization.

2021-08-16 04:18 UTC, vania-pooh commented on build/edge.go
> +		err := os.MkdirAll(devDestDir+"/"+srcDir, 0755)
Use `filepath.Join`.

2021-08-16 04:18 UTC, vania-pooh commented on build/firefox.go
> +		err := os.MkdirAll(devDestDir+"/"+devSrcDir, 0755)
Use `filepath.Join`.

2021-08-16 04:18 UTC, vania-pooh commented on build/opera.go
> +		err := os.MkdirAll(devDestDir+"/"+srcDir, 0755)
Use `filepath.Join`.

2021-08-16 04:18 UTC, vania-pooh commented on build/yandex.go
> +		err := os.MkdirAll(devDestDir+"/"+srcDir, 0755)
Use `filepath.Join`.

2021-08-16 11:53 UTC, vania-pooh approved these changes

2021-08-16 11:53 UTC, merged

2021-08-16 11:54 UTC, vania-pooh commented
@lorsatti thank you for contribution!